### ISSUE TITLE
Update Vulnerabilietes: Error 404 downloading RHEL3.xml on "quay.io/redhat/clair-jwt:v3.2.1"

### ISSUE THREAD

**Issue by dawidek88** [quay/clair-jwt#28]
If the Clair Scanner started and ran the update script little bit later - an error was displayed.

{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2020-04-20 13:24:25.204396","error":"received 404 code downloading https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL3.xml","updater name":"rhel"}

FYI: The file does not exists on the page: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL3.xml. What can I do?

**Comment by dawidek88** [comment]
I tried to build the docker image with "make centos7-build-env rhel7 GIT_TAG=v2.0.9 SUBSCRIPTION_KEY=<my key>.pem" but I got an error.

**"Step 23/26 : RUN go get -u -d github.com/coreos/clair/cmd/clair
 ---> Running in 847414df7f4e
package github.com/quay/clair/api: code in directory /go/src/github.com/quay/clair/api expects import "github.com/quay/clair/v3/api"
# cd /go/src/github.com/asottile/dockerfile/vendor/github.com/moby/buildkit; git pull --ff-only
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/asottile/dockerfile/vendor/github.com/moby/buildkit/frontend/dockerfile/command: exit status 1
The command '/bin/sh -c go get -u -d github.com/coreos/clair/cmd/clair' returned a non-zero code: 1
make: *** [Makefile:7: centos7-build-env] Error 1"**


Can someone help me, please. I do not know, how to fix it.

**Comment by samm-git** [comment]
@dawidek88 i fixed build for the alpine, see https://github.com/quay/clair-jwt/pull/29
